const icons = [
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 0,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 1,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 2,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 3,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 4,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 5,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 6,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 7,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 8,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 9,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 10,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 11,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 12,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 13,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 14,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 15,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 16,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 17,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 18,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 19,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 20,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 21,
    },
    {
      "src": "img/hero_bg_2.jpg",
      "type": "img/hero--2.svg",
      "sizes": "512x512",
      "id": 22,
    },
    {
      "src": "img/hero_bg_3.svg",
      "type": "img/hero--3.svg",
      "sizes": "512x512",
      "id": 23,
    },
    {
      "src": "img/hero_bg_1.svg",
      "type": "img/hero--1.svg",
      "sizes": "192x192",
      "id": 24,
    },
];

export default icons;